name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -f DOCKERFILE -t sbg-website .

      - name: Extract Compiled Files
        run: |
          mkdir -p deploy/server deploy/client
          docker create --name temp-container sbg-website
          # Copy Backend files
          docker cp temp-container:/app/server/dist ./deploy/server/
          docker cp temp-container:/app/server/package.json ./deploy/server/
          # Copy Frontend files (the dist is served from /app/client)
          docker cp temp-container:/app/client ./deploy/client/
          docker rm temp-container
          
          # We also need the package-lock.json for clean installs on the server
          cp server/package-lock.json ./deploy/server/