name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to CentOS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/SBG_Website
            git pull origin main
            cd server
            npm install
            npm run build
            pm2 restart sbg-website-be
